version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:80" # Map port 80 of the container to port 8000 on the host
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=ppe_management
      - DB_USERNAME=root
      - DB_PASSWORD=

  db:
    image: mysql:5.7
    container_name: mysql_db
    ports:
      - "3307:3306" # Map port 3306 of the container to port 3307 on the host
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
